[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.install]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/taskmanager-0.0.1-SNAPSHOT.jar"
